---
settings:
  name: Release Notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Versionshinweise zu BlueXP
    url: "/index.html"
  - title: Neueste Änderungen
    url: "/whats-new.html"
  - title: Versionshinweisen – Index
    url: "/release-notes-index.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
