---
settings:
  name: Release Notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Versionshinweise zu BlueXP
    url: "/index.html"
  - title: Neueste Änderungen
    url: "/whats-new.html"
  - title: BlueXP-Index
    url: "/release-notes-index.html"
homepage:
  tiles:
  - title: Was ist neu
    links:
    - title: Aktuelle Änderungen in BlueXP
      url: whats-new.html
  - title: Versionshinweise nach Service
    links:
    - title: Versionshinweisen – Index
      url: release-notes-index.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog der BlueXP-Website
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
