---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: Erfahren Sie mehr über die neuesten Änderungen an den Cloud-Services, die Teil der BlueXP Plattform sind. 
---
= Aktuelle Änderungen in BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die neuesten Änderungen an den Cloud-Services, die Teil der BlueXP Plattform sind. Einen vollständigen Versionsverlauf finden Sie im link:release-notes-index.html["Vollständiger Satz an Versionshinweisen"] Für jeden einzelnen Service.



== Administrative Funktionen

In diesem Abschnitt werden neue Funktionen in Bezug auf BlueXP-Verwaltungsfunktionen beschrieben: Konten, Connectors, Anmeldeinformationen für Cloud-Provider und mehr.



=== 14 Juli 2025



==== Connector 3.9.54

Diese Version des BlueXP Connectors enthält Sicherheitsverbesserungen, Fehlerbehebungen und die folgenden neuen Funktionen:

* Unterstützung für transparente Proxys für Connectors, die speziell für die Unterstützung von Cloud Volumes ONTAP Diensten vorgesehen sind. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Erfahren Sie mehr über die Konfiguration eines transparenten Proxys."]
* Möglichkeit zur Verwendung von Netzwerk-Tags zur Weiterleitung des Connector-Datenverkehrs, wenn der Connector in einer Google Cloud-Umgebung bereitgestellt wird.
* Zusätzliche produktinterne Benachrichtigungen zur Überwachung des Connector-Zustands, einschließlich CPU- und RAM-Auslastung.


Derzeit ist die Version 3.9.54 für den Standardmodus und den eingeschränkten Modus verfügbar.



==== Identitäts- und Zugriffsmanagement (BlueXP , IAM)

Identity and Access Management in BlueXP bietet jetzt die folgenden Funktionen:

* Unterstützung für IAM im privaten Modus, sodass Sie den Benutzerzugriff und die Berechtigungen für BlueXP -Dienste und -Anwendungen verwalten können.
* Optimierte Verwaltung von Identitätsföderationen, einschließlich einfacherer Navigation, klarerer Optionen zum Konfigurieren föderierter Verbindungen und verbesserter Transparenz in vorhandenen Föderationen.
* Zugriffsrollen für BlueXP backup and recovery, BlueXP disaster recovery und Föderationsverwaltung.




===== Unterstützung für IAM im privaten Modus

BlueXP unterstützt jetzt IAM im privaten Modus und ermöglicht Ihnen die Verwaltung von Benutzerzugriff und Berechtigungen für BlueXP -Dienste und -Anwendungen. Diese Erweiterung ermöglicht es Kunden im privaten Modus, die rollenbasierte Zugriffskontrolle (RBAC) für mehr Sicherheit und Compliance zu nutzen.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["Erfahren Sie mehr über IAM in BlueXP."]



===== Optimierte Verwaltung von Identitätsföderationen

BlueXP bietet jetzt eine intuitivere Benutzeroberfläche für die Verwaltung der Identitätsföderation. Dies umfasst eine einfachere Navigation, übersichtlichere Optionen zur Konfiguration föderierter Verbindungen und eine verbesserte Transparenz bestehender Föderationen.

Durch die Aktivierung von Single Sign-On (SSO) über die Identitätsföderation können sich Benutzer mit ihren Unternehmensanmeldeinformationen bei BlueXP anmelden. Dies erhöht die Sicherheit, reduziert die Passwortnutzung und vereinfacht das Onboarding.

Sie werden aufgefordert, alle vorhandenen Verbundverbindungen in die neue Benutzeroberfläche zu importieren, um Zugriff auf die neuen Verwaltungsfunktionen zu erhalten. So können Sie die neuesten Verbesserungen nutzen, ohne Ihre Verbundverbindungen neu erstellen zu müssen. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["Erfahren Sie mehr über das Importieren Ihrer vorhandenen Verbundverbindung zu BlueXP."]

Durch die verbesserte Föderationsverwaltung können Sie:

* Fügen Sie einer Verbundverbindung mehr als eine verifizierte Domäne hinzu, sodass Sie mehrere Domänen mit demselben Identitätsanbieter (IdP) verwenden können.
* Deaktivieren oder löschen Sie Verbundverbindungen nach Bedarf und behalten Sie so die Kontrolle über Benutzerzugriff und Sicherheit.
* Steuern Sie den Zugriff auf die Föderationsverwaltung mit IAM-Rollen.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["Erfahren Sie mehr über die Identitätsföderation in BlueXP."]



===== Neue Zugriffsrollen für BlueXP backup and recovery, BlueXP disaster recovery und Federation Management

BlueXP unterstützt jetzt die Verwendung von IAM-Rollen für die folgenden Funktionen und Datendienste:

* BlueXP Backup und Recovery
* BlueXP Disaster Recovery
* Föderation


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über die Verwendung von Zugriffsrollen."]



=== 9 Juni 2025



==== Konnektor 3.9.53

Diese Version des BlueXP Connector enthält Sicherheitsverbesserungen und Fehlerbehebungen.

Die Version 3.9.53 ist für den Standardmodus und den eingeschränkten Modus verfügbar.



==== Warnmeldungen zur Speicherplatznutzung

Das Benachrichtigungscenter enthält jetzt Warnungen zur Speicherplatznutzung auf dem Connector. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["Weitere Informationen ."^]



==== Audit-Verbesserungen

Die Zeitleiste enthält jetzt Anmelde- und Abmeldeereignisse für Benutzer. Sie können die Anmeldeaktivität sehen, was bei der Prüfung und Sicherheitsüberwachung hilfreich sein kann. API-Benutzer mit der Rolle „Organisationsadministrator“ können die E-Mail-Adresse des angemeldeten Benutzers anzeigen, indem sie Folgendes angeben:  `includeUserData=true`` Parameter wie folgt:  `/audit/<account_id>?includeUserData=true` .



==== Keystone-Abonnementverwaltung in BlueXP verfügbar

Sie können Ihr NetApp Keystone-Abonnement von BlueXP aus verwalten.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Erfahren Sie mehr über die Verwaltung von Keystone-Abonnements in BlueXP."^]



==== Identitäts- und Zugriffsmanagement (BlueXP , IAM)



===== Multi-Faktor-Authentifizierung (MFA)

Nicht föderierte Benutzer können MFA für ihre BlueXP -Konten aktivieren, um die Sicherheit zu verbessern. Administratoren können MFA-Einstellungen verwalten und MFA für Benutzer bei Bedarf zurücksetzen oder deaktivieren. Dies wird nur im Standardmodus unterstützt.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Erfahren Sie, wie Sie die Multi-Faktor-Authentifizierung selbst einrichten."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["Erfahren Sie mehr über die Verwaltung der Multi-Faktor-Authentifizierung für Benutzer."^]



==== Workloads

Sie können jetzt Anmeldeinformationen für Amazon FSx für NetApp ONTAP auf der Seite „Anmeldeinformationen“ in BlueXP anzeigen und löschen.



=== 29 Mai 2025



==== Freigabe des Privatmodus (3.9.52)

Eine neue Version für den privaten Modus steht jetzt zum Herunterladen von zur Verfügung https://mysupport.netapp.com/site/downloads["NetApp Support-Website"^]

Die Version 3.9.52 enthält Updates für die folgenden BlueXP-Komponenten und -Dienste.

[cols="3*"]
|===
| Komponente oder Dienst | In dieser Version enthaltene Version | Änderungen seit der letzten privaten Modus-Freigabe 


| Stecker | 3.9.52, 3.9.51 | Gehen Sie zum  https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["Was ist neu in BlueXP  Connector Seite"] und beziehen Sie sich auf die Änderungen, die in den Versionen 3.9.52 und 3.9.50 enthalten sind. 


| Backup und Recovery | 12 Mai 2025 | Gehen Sie zum  https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["Was ist neu auf der Backup- und Recovery-Seite von BlueXP"^] und beziehen Sie sich auf die Änderungen, die in der Version vom Mai 2025 enthalten sind. 


| Klassifizierung | 12. Mai 2025 (Version 1.43) | Rufen Sie die https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["Was ist neu in der BlueXP  Klassifizierungsseite"^] auf und beziehen Sie sich auf die Änderungen der Versionen 1.38 bis 1.371.41. 
|===
Weitere Informationen zum privaten Modus, einschließlich der Aktualisierung, finden Sie in den folgenden Informationen:

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Weitere Informationen zum privaten Modus"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Erfahren Sie mehr über die ersten Schritte mit BlueXP im privaten Modus"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Erfahren Sie, wie Sie den Connector bei der Verwendung des privaten Modus aktualisieren"]




== Meldungen



=== 7 Oktober 2024



==== Seite mit der BlueXP -Meldungsliste

ONTAP-Cluster mit geringer Kapazität oder niedriger Performance lassen sich schnell identifizieren, Verfügbarkeitsgrenzen überprüfen und Sicherheitsrisiken identifizieren. Sie können Warnmeldungen zu Kapazität, Performance, Sicherung, Verfügbarkeit, Sicherheit und Konfiguration anzeigen.



==== Alarmdetails

Sie können Details zu Warnmeldungen anzeigen und Empfehlungen finden.



==== Zeigen Sie mit dem ONTAP System Manager verknüpfte Cluster-Details an

Dank BlueXP -Warnmeldungen lassen sich Warnmeldungen zu Ihrer ONTAP Storage-Umgebung anzeigen sowie Details anzeigen, die mit ONTAP System Manager verknüpft sind.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Informieren Sie sich über BlueXP -Warnmeldungen"].



== Amazon FSX für ONTAP



=== 14 Juli 2025



==== Unterstützung für die Replikation von Daten zwischen zwei FSx for ONTAP-Dateisystemen

Die Datenreplikation zwischen zwei FSx für ONTAP-Dateisystemen ist jetzt über die BlueXP-Konsole verfügbar.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["Datenreplizierung"]



=== 29 Juni 2025



==== Aktualisierung der Anmeldeinformationen

Nachdem Sie Anmeldeinformationen und Berechtigungen für Ihr FSx for ONTAP-Dateisystem eingerichtet haben, werden Sie zur Seite „BlueXP-Anmeldeinformationen“ weitergeleitet. Auf dieser Seite können Sie Ihre FSx for ONTAP-Anmeldeinformationen umbenennen oder entfernen.

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["Einrichten von Berechtigungen für FSx for ONTAP-Dateisysteme"]



=== 04 Mai 2025



==== Unterstützung von Tracker-Antworten

Tracker bietet jetzt API-Antworten, sodass Sie die REST API-Ausgabe zu der Aufgabe sehen können.



==== Unterstützung der Link-Authentifizierung für AWS Secrets Manager

Sie haben jetzt die Möglichkeit, Secrets von AWS Secrets Manager zum Authentifizieren von Links zu verwenden, sodass Sie keine in BlueXP -Workloads gespeicherten Anmeldeinformationen verwenden müssen.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Stellen Sie über einen Lambda-Link eine Verbindung zu einem FSX für ONTAP-Dateisystem her"]



==== Implementierung von Best Practices für ein FSX für ONTAP-Filesystem

BlueXP  Workloads bietet ein Dashboard, über das Sie den Architektur-Status Ihrer Filesystem-Konfigurationen überprüfen können. Mithilfe dieser Analyse können Sie Best Practices für Ihre FSX for ONTAP-Dateisysteme implementieren. Die Dateisystemkonfigurationsanalyse umfasst die folgenden Konfigurationen: SSD-Kapazitätsgrenze, geplante lokale Snapshots, geplante FSX für ONTAP-Backups, Daten-Tiering und Remote-Datenreplizierung.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Informieren Sie sich über die gut konzipierte Analyse für Filesystem-Konfigurationen"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implementieren Sie Best Practices für Ihre Dateisysteme"]




==== Gut gestaltete Benachrichtigung bei Problemen mit dem Dateisystem

In der BlueXP -Konsole zeigen FSX für ONTAP-Dateisysteme mit gut konzipierten Problemen jetzt eine Benachrichtigung im Bildschirm an, die anzeigt, wann Dateisysteme Probleme zu beheben haben.



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



== Amazon S3 Storage



=== 5 März 2023



==== Möglichkeit zum Hinzufügen neuer Buckets aus BlueXP

Sie können Amazon S3 Buckets seit geraumer Zeit auf dem BlueXP Canvas anzeigen. Jetzt können Sie neue Buckets hinzufügen und Eigenschaften für vorhandene Buckets direkt aus BlueXP  ändern. https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["So fügen Sie neue Amazon S3 Buckets hinzu"].



== Azure Blob Storage



=== 5 Juni 2023



==== Hinzufügen neuer Storage-Konten von BlueXP möglich

Sie haben schon lange die Möglichkeit, Azure Blob Storage auf dem BlueXP-Bildschirm anzuzeigen. Sie können jetzt direkt aus BlueXP  neue Storage-Konten hinzufügen und Eigenschaften vorhandener Storage-Konten ändern. https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["Hier erfahren Sie, wie Sie neue Azure Blob Storage-Konten hinzufügen"].



== Azure NetApp Dateien



=== 13 Januar 2025



==== Netzwerkfunktionen werden jetzt in BlueXP  unterstützt

Wenn Sie ein Volume in Azure NetApp Files über BlueXP  konfigurieren, können Sie jetzt Netzwerkfunktionen angeben. Dies harmonisiert mit den in nativen Azure NetApp Files verfügbaren Funktionen.



=== 12 Juni 2024



==== Neue Berechtigung erforderlich

Für das Management von Azure NetApp Files Volumes von BlueXP ist jetzt die folgende Berechtigung erforderlich:

Microsoft.Network/virtualNetworks/subnets/read

Diese Berechtigung ist erforderlich, um ein virtuelles Netzwerk-Subnetz zu lesen.

Wenn Sie derzeit Azure NetApp Files aus BlueXP managen, müssen Sie diese Berechtigung der benutzerdefinierten Rolle hinzufügen, die mit der zuvor erstellten Microsoft Entra-Applikation verknüpft ist.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["Erfahren Sie, wie Sie eine Microsoft Entra-Anwendung einrichten und die benutzerdefinierten Rollenberechtigungen anzeigen"].



=== Bis 22. April 2024



==== Volume-Vorlagen werden nicht mehr unterstützt

Sie können kein Volume mehr aus einer Vorlage erstellen. Diese Aktion wurde mit dem BlueXP Korrekturservice verknüpft, der nicht mehr verfügbar ist.



== Backup und Recovery



=== 14 Juli 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



==== Verbessertes ONTAP Volume Dashboard

Im April 2025 haben wir eine Vorschau eines verbesserten ONTAP Volume Dashboards veröffentlicht, das viel schneller und effizienter ist.

Dieses Dashboard wurde speziell für Unternehmenskunden mit hohen Workloads entwickelt. Selbst für Kunden mit 20.000 Volumes wird das neue Dashboard in weniger als 10 Sekunden geladen.

Nach einer erfolgreichen Vorschau und dem großartigen Feedback unserer Kunden machen wir es nun zur Standarderfahrung für alle unsere Kunden. Freuen Sie sich auf ein blitzschnelles Dashboard.

Weitere Informationen finden Sie unter link:br-use-dashboard.html["Anzeigen des Schutzstatus im Dashboard"].



==== Microsoft SQL Server-Workload-Unterstützung als Public Technology Preview

Diese Version von BlueXP backup and recovery bietet eine aktualisierte Benutzeroberfläche, mit der Sie Microsoft SQL Server-Workloads mithilfe der 3-2-1-Schutzstrategie verwalten können, die Sie vom BlueXP backup and recovery Dienst kennen. Mit der neuen Version können Sie diese Workloads auf dem Primärspeicher sichern, auf dem Sekundärspeicher replizieren und in einem Cloud-Objektspeicher sichern.

Sie können sich für die Vorschau anmelden, indem Sie dieses Formular ausfüllen.  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Vorschau des Anmeldeformulars"^] .


NOTE: DIESE DOKUMENTATION ZUM SCHUTZ VON MICROSOFT SQL SERVER-WORKLOADS WIRD ALS TECHNOLOGIEVORSCHAU BEREITGESTELLT. Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

Diese Version von BlueXP backup and recovery enthält die folgenden Updates:

* *3-2-1-Backup-Funktion*: Diese Version integriert SnapCenter -Funktionen und ermöglicht Ihnen die Verwaltung und den Schutz Ihrer SnapCenter Ressourcen mit einer 3-2-1-Datensicherungsstrategie über die BlueXP backup and recovery .
* *Import aus SnapCenter*: Sie können SnapCenter -Sicherungsdaten und -Richtlinien in BlueXP backup and recovery importieren.
* *Eine neu gestaltete Benutzeroberfläche* ermöglicht eine intuitivere Verwaltung Ihrer Sicherungs- und Wiederherstellungsaufgaben.
* *Sicherungsziele*: Sie können Buckets in Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID und ONTAP S3-Umgebungen hinzufügen, um sie als Sicherungsziele für Ihre Microsoft SQL Server-Workloads zu verwenden.
* *Workload-Unterstützung*: Mit dieser Version können Sie Microsoft SQL Server-Datenbanken und Verfügbarkeitsgruppen sichern, wiederherstellen, überprüfen und klonen. (Die Unterstützung für weitere Workloads wird in zukünftigen Versionen hinzugefügt.)
* *Flexible Wiederherstellungsoptionen*: Mit dieser Version können Sie Datenbanken im Falle einer Beschädigung oder eines versehentlichen Datenverlusts sowohl am ursprünglichen als auch an alternativen Speicherorten wiederherstellen.
* *Sofortige Produktionskopien*: Erstellen Sie platzsparende Produktionskopien für Entwicklung, Tests oder Analysen in Minuten statt in Stunden oder Tagen.
* Diese Version beinhaltet die Möglichkeit, detaillierte Berichte zu erstellen.


Weitere Informationen zum Schutz von Microsoft SQL Server-Workloads finden Sie unter link:br-use-mssql-protect-overview.html["Übersicht zum Schützen von Microsoft SQL Server-Workloads"] .



=== 09 Juni 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



==== Updates zur Unterstützung indizierter Kataloge

Im Februar 2025 haben wir die aktualisierte Indizierungsfunktion (Indexed Catalog v2) eingeführt, die Sie bei der Datenwiederherstellung mit der Methode „Suchen und Wiederherstellen“ verwenden. Die vorherige Version verbesserte die Leistung der Datenindizierung in lokalen Umgebungen deutlich. Mit dieser Version ist der Indizierungskatalog nun in Amazon Web Services-, Microsoft Azure- und Google Cloud Platform (GCP)-Umgebungen verfügbar.

Für Neukunden ist der Indexed Catalog v2 standardmäßig für alle neuen Umgebungen aktiviert. Bestandskunden können ihre Umgebung neu indizieren, um den Indexed Catalog v2 zu nutzen.

.Wie aktivieren Sie die Indexierung?
Bevor Sie die Such- und Wiederherstellungsmethode zum Wiederherstellen von Daten verwenden können, müssen Sie „Indizierung“ in jeder Quellarbeitsumgebung aktivieren, in der Sie Volumes oder Dateien wiederherstellen möchten. Wählen Sie die Option *Indizierung aktivieren*, wenn Sie eine Suche und Wiederherstellung durchführen.

Der indizierte Katalog kann dann jedes Volume und jede Sicherungsdatei verfolgen, sodass Ihre Suchvorgänge schnell und effizient erfolgen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Wiederherstellen von ONTAP-Daten mithilfe von Suche  Wiederherstellen"].



==== Azure Private Link-Endpunkte und Dienstendpunkte

Normalerweise richtet BlueXP Backup & Recovery einen privaten Endpunkt beim Cloud-Anbieter ein, um verschiedene Schutzaufgaben zu übernehmen. Diese Version bietet eine optionale Einstellung, mit der Sie die automatische Erstellung eines privaten Endpunkts durch BlueXP Backup & Recovery aktivieren oder deaktivieren können. Dies ist hilfreich, wenn Sie mehr Kontrolle über die Erstellung des privaten Endpunkts wünschen.

Sie können diese Option aktivieren oder deaktivieren, wenn Sie den Schutz aktivieren oder den Wiederherstellungsprozess starten.

Wenn Sie diese Einstellung deaktivieren, müssen Sie den privaten Endpunkt manuell erstellen, damit die BlueXP-Sicherung und -Wiederherstellung ordnungsgemäß funktioniert. Ohne die richtige Konnektivität können Sie Sicherungs- und Wiederherstellungsaufgaben möglicherweise nicht erfolgreich durchführen.



==== Unterstützung für SnapMirror zur Cloud-Resynchronisierung auf ONTAP S3

Die vorherige Version unterstützte SnapMirror to Cloud Resync (SM-C Resync). Diese Funktion optimiert den Datenschutz bei der Volumemigration in NetApp-Umgebungen. Diese Version unterstützt SM-C Resync auf ONTAP S3 sowie anderen S3-kompatiblen Anbietern wie Wasabi und MinIO.



==== Bringen Sie Ihren eigenen Bucket für StorageGRID mit

Wenn Sie Sicherungsdateien im Objektspeicher für eine Arbeitsumgebung erstellen, erstellt BlueXP Backup & Recovery standardmäßig den Container (Bucket oder Speicherkonto) für die Sicherungsdateien im von Ihnen konfigurierten Objektspeicherkonto. Bisher konnten Sie dies überschreiben und Ihren eigenen Container für Amazon S3, Azure Blob Storage und Google Cloud Storage angeben. Mit dieser Version können Sie nun Ihren eigenen StorageGRID-Objektspeichercontainer verwenden.

Siehe https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Erstellen Sie Ihren eigenen Objektspeichercontainer"].



=== 13 Mai 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



==== Neusynchronisierung von SnapMirror zu Cloud bei Volume-Migrationen

Die Funktion SnapMirror zu Cloud Resync optimiert die Datensicherung und Kontinuität bei Volume-Migrationen in NetApp-Umgebungen. Bei der Migration eines Volumes mithilfe von SnapMirror Logical Replication (LRSE), von einer lokalen NetApp Implementierung zu einer anderen oder zu einer Cloud-basierten Lösung wie Cloud Volumes ONTAP oder Cloud Volumes Service sorgt SnapMirror zu Cloud Resync dafür, dass vorhandene Cloud-Backups intakt und betriebsbereit bleiben.

Durch diese Funktion wird ein zeitaufwendiger und ressourcenintensiver Neustart des Basisplans überflüssig, sodass Backup-Vorgänge nach der Migration fortgesetzt werden können. Diese Funktion ist in Workload-Migrationsszenarien nützlich, da sie sowohl FlexVols als auch FlexGroups unterstützt. Sie ist ab ONTAP Version 9.16.1 verfügbar.

Durch die Aufrechterhaltung der Backup-Kontinuität über verschiedene Umgebungen hinweg verbessert SnapMirror to Cloud Resync die betriebliche Effizienz und verringert die Komplexität des Datenmanagements in der Hybrid Cloud und Multi Cloud.

Weitere Informationen zur Durchführung der Resynchronisierung finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["Migrieren Sie Volumes mit SnapMirror zur Cloud-Neusynchronisierung"].



==== Unterstützung für Minio-Objektspeicher von Drittanbietern (Vorschau)

Backup und Recovery von BlueXP  erweitern jetzt ihre Unterstützung auf Objektspeicher anderer Hersteller, wobei der Schwerpunkt auf Mini-Objektspeicher liegt. Mit dieser neuen Vorschaufunktion können Sie jeden S3-kompatiblen Objektspeicher für Ihre Backup- und Recovery-Anforderungen nutzen.

Mit dieser Vorschau-Version möchten wir eine robuste Integration in Objektspeicher von Drittanbietern gewährleisten, bevor die volle Funktionalität verfügbar ist. Wir empfehlen Ihnen, diese neue Funktion zu erkunden und Feedback zu geben, um den Service zu verbessern.


IMPORTANT: Diese Funktion sollte nicht in der Produktion verwendet werden.

*Beschränkungen des Vorschaumodus*

Während diese Funktion in der Vorschau angezeigt wird, gibt es einige Einschränkungen:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt.
* Die Aktivierung von DataLock in der Richtlinie wird nicht unterstützt.
* Die Aktivierung des Archivmodus in der Richtlinie wird nicht unterstützt.
* Es werden nur lokale ONTAP-Umgebungen unterstützt.
* MetroCluster wird nicht unterstützt.
* Optionen zur Aktivierung der Verschlüsselung auf Bucket-Ebene werden nicht unterstützt.


*Erste Schritte*

Um diese Vorschaufunktion zu verwenden, müssen Sie ein Flag auf dem BlueXP -Konnektor aktivieren. Sie können dann die Verbindungsdetails Ihres Minio-Objektspeichers von Drittanbietern im Schutz-Workflow eingeben, indem Sie im Backup-Bereich den Objektspeicher *Drittanbieter-kompatibel* auswählen.

Anweisungen zum Aktivieren von Vorschaufunktionen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["Aktivieren Sie Vorschaufunktionen für BlueXP  Backup und Recovery"].



=== Bis 16. April 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



==== UI-Verbesserungen

Diese Version verbessert die Benutzerfreundlichkeit durch die Vereinfachung der Oberfläche:

* Das Entfernen der Spalte Aggregate aus den Volume-Tabellen zusammen mit den Spalten Snapshot Policy, Backup Policy und Replication Policy aus der Volume-Tabelle im V2 Dashboard führt zu einem optimierten Layout.
* Wenn Sie nicht aktivierte Arbeitsumgebungen aus der Dropdown-Liste ausschließen, wird die Oberfläche weniger überladen, die Navigation effizienter und das Laden schneller.
* Während die Sortierung in der Spalte Tags deaktiviert ist, können Sie die Tags dennoch anzeigen, um sicherzustellen, dass wichtige Informationen leicht zugänglich bleiben.
* Das Entfernen von Etiketten auf den Schutzsymbolen trägt zu einem saubereren Aussehen bei und verringert die Ladezeit.
* Während der Aktivierung der Arbeitsumgebung wird in einem Dialogfeld ein Ladesymbol angezeigt, das Feedback liefert, bis der Erkennungsvorgang abgeschlossen ist. Dies erhöht die Transparenz und erhöht die Sicherheit für die Systemvorgänge.




==== Verbessertes Volume Dashboard (Vorschau)

Das Volume Dashboard kann jetzt in weniger als 10 Sekunden geladen werden und bietet damit eine wesentlich schnellere und effizientere Schnittstelle. Diese Vorschau-Version ist für ausgewählte Kunden verfügbar und bietet ihnen einen ersten Blick auf diese Verbesserungen.



==== Unterstützung für Wasabi-Objektspeicher von Drittanbietern (Vorschau)

BlueXP  Backup und Recovery erweitert jetzt ihre Unterstützung auf Objektspeicher von Drittanbietern, wobei der Schwerpunkt primär auf Wasabi liegt. Mit dieser neuen Vorschaufunktion können Sie jeden S3-kompatiblen Objektspeicher für Ihre Backup- und Recovery-Anforderungen nutzen.



===== Erste Schritte mit Wasabi

Um Drittanbieter-Storage als Objektspeicher zu verwenden, müssen Sie im BlueXP -Connector ein Flag aktivieren. Anschließend können Sie die Verbindungsdetails für einen Objektspeicher eines Drittanbieters eingeben und in Ihre Backup- und Recovery-Workflows integrieren.

.Schritte
. SSH in den Connector.
. Gehen Sie zum cbs-Server-Container für Backup und Recovery von BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Öffnen Sie die `default.json` Datei im `config` Ordner über VIM oder einen anderen Editor:
+
[listing]
----
vi default.json
----
. Ändern `allow-s3-compatible`: false zu `allow-s3-compatible`: true.
. Speichern Sie die Änderungen.
. Verlassen Sie den Container.
. Starten Sie den cbs-Server-Container für BlueXP  Backup und Recovery neu.


.Ergebnis
Nachdem der Container wieder EINGESCHALTET ist, öffnen Sie die BlueXP  Backup and Recovery UI. Wenn Sie ein Backup initiieren oder eine Backup-Strategie bearbeiten, wird der neue Provider zusammen mit anderen Backup-Providern von AWS, Microsoft Azure, Google Cloud, StorageGRID und ONTAP S3 als „S3-kompatibel“ aufgeführt.



===== Einschränkungen des Vorschaumodus

Während diese Funktion in der Vorschau angezeigt wird, beachten Sie die folgenden Einschränkungen:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt.
* Die Aktivierung von DataLock in einer Richtlinie wird nicht unterstützt.
* Die Aktivierung des Archivmodus in einer Richtlinie wird nicht unterstützt.
* Es werden nur lokale ONTAP-Umgebungen unterstützt.
* MetroCluster wird nicht unterstützt.
* Optionen zur Aktivierung der Verschlüsselung auf Bucket-Ebene werden nicht unterstützt.


In dieser Vorschau empfehlen wir Ihnen, diese neue Funktion zu erkunden und Feedback zur Integration in Objektspeicher von Drittanbietern zu geben, bevor die volle Funktionalität bereitgestellt wird.



== Klassifizierung



=== 14 Juli 2025



==== Version 1.45

Diese BlueXP classification Klassifizierungsversion enthält Codeänderungen, die die Ressourcennutzung optimieren und:

.Verbesserter Workflow zum Hinzufügen von Dateifreigaben zum Scannen
Der Workflow zum Hinzufügen von Dateifreigaben zu einer Dateifreigabegruppe wurde vereinfacht. Der Prozess unterscheidet jetzt auch die CIFS-Protokollunterstützung basierend auf dem Authentifizierungstyp (Kerberos oder NTLM).

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Scannen von Dateifreigaben"].

.Erweiterte Informationen zum Dateieigentümer
Sie können jetzt weitere Informationen zu Dateibesitzern für erfasste Dateien auf der Registerkarte „Untersuchung“ anzeigen. Suchen Sie beim Anzeigen der Metadaten für eine Datei auf der Registerkarte „Untersuchung“ den Dateibesitzer und wählen Sie dann **Details anzeigen** aus, um den Benutzernamen, die E-Mail-Adresse und den SAM-Kontonamen anzuzeigen. Sie können auch andere Elemente anzeigen, die diesem Benutzer gehören. Diese Funktion ist nur in Arbeitsumgebungen mit Active Directory verfügbar.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten"].



=== 10 Juni 2025



==== Version 1.44

Diese BlueXP -Klassifizierungsversion umfasst:

.Verbesserte Aktualisierungszeiten für das Governance-Dashboard
Die Aktualisierungszeiten für einzelne Komponenten des Governance-Dashboards wurden verbessert. Die folgende Tabelle zeigt die Aktualisierungshäufigkeit für jede Komponente.

[cols="1,1"]
|===
| Komponente | Aktualisierungszeiten 


| Alter der Daten | 24 Stunden 


| Kategorien | 24 Stunden 


| Datenüberblick | 5 Minuten 


| Doppelte Dateien | 2 Stunden 


| Dateitypen | 24 Stunden 


| Nicht-Geschäftsdaten | 2 Stunden 


| Öffnen Sie Berechtigungen | 24 Stunden 


| Gespeicherte Suchen | 2 Stunden 


| Sensible Daten und umfassende Berechtigungen | 24 Stunden 


| Größe von Daten | 24 Stunden 


| Veraltete Daten | 2 Stunden 


| Top-Datenspeicher nach Vertraulichkeitsstufe | 2 Stunden 
|===
Sie können den Zeitpunkt der letzten Aktualisierung anzeigen und die Komponenten „Doppelte Dateien“, „Nicht-Geschäftsdaten“, „Gespeicherte Suchen“, „Veraltete Daten“ und „Top-Datenrepositorys nach Vertraulichkeitsstufe“ manuell aktualisieren. Weitere Informationen zum Governance-Dashboard finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Zeigen Sie Governance-Details zu den in Ihrer Organisation gespeicherten Daten an"] .

.Leistungs- und Sicherheitsverbesserungen
Es wurden Verbesserungen vorgenommen, um die Leistung, den Speicherverbrauch und die Sicherheit der BlueXP-Klassifizierung zu verbessern.

.Fehlerbehebungen
Redis wurde aktualisiert, um die Zuverlässigkeit der BlueXP-Klassifizierung zu verbessern. Die BlueXP-Klassifizierung verwendet jetzt Elasticsearch, um die Genauigkeit der Dateianzahlberichterstattung während Scans zu verbessern.



=== 12 Mai 2025



==== Version 1.43

Diese BlueXP -Klassifizierungsversion umfasst:

.Priorisieren Sie Klassifizierungs-Scans
Die BlueXP -Klassifizierung unterstützt die Möglichkeit, neben den nur-Mapping-Scans auch Karten- und Klassifikationsscans zu priorisieren, wodurch Sie auswählen können, welche Scans zuerst abgeschlossen werden. Die Priorisierung von Map & Classify-Scans wird während und vor Beginn der Scans unterstützt. Wenn Sie einen Scan priorisieren möchten, während er gerade läuft, werden sowohl die Mapping- als auch die Klassifikationsscans priorisiert.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorisieren Sie Scans"].

.Unterstützung für kanadische Datenkategorien für personenbezogene Daten (PII)
BlueXP -Klassifikations-Scans identifizieren kanadische PII-Datenkategorien. Diese Kategorien umfassen Bankdaten, Passnummern, Sozialversicherungsnummern, Führerscheinnummern und Krankenkartennummern für alle kanadischen Provinzen und Gebiete.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Kategorien personenbezogener Daten"].

.Benutzerdefinierte Klassifizierung (Vorschau)
Die BlueXP -Klassifizierung unterstützt benutzerdefinierte Klassifizierungen für Karten- und Klassifikations-Scans. Mit benutzerdefinierten Klassifizierungen können Sie BlueXP -Scans so anpassen, dass sie Daten erfassen, die speziell auf Ihr Unternehmen zugeschnitten sind, und dabei reguläre Ausdrücke verwenden. Diese Funktion befindet sich derzeit in der Vorschau.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["Fügen Sie benutzerdefinierte Klassifizierungen hinzu"].

.Registerkarte gespeicherte Suchen
Die Registerkarte **Policen** wurde umbenanntlink:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**Gespeicherte Suchen**"]. Die Funktionalität bleibt unverändert.

.Senden Sie Scanereignisse an die BlueXP  Timeline
BlueXP  Classification unterstützt das Senden von Klassifikationsereignissen (wenn ein Scan initiiert wird und wann er endet) an den link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  Zeitplan"^].

.Sicherheitsupdates
* Das Keras-Paket wurde aktualisiert, um Schwachstellen zu beheben (BDSA-2025-0107 und BDSA-2025-1984).
* Die Konfiguration der Docker Container wurde aktualisiert. Der Container hat keinen Zugriff mehr auf die Netzwerkschnittstellen des Hosts, um rohe Netzwerkpakete zu erstellen. Durch die Reduzierung unnötiger Zugriffe verringert das Update potenzielle Sicherheitsrisiken.


.Performance-Verbesserungen
Codeverbesserungen wurden implementiert, um die RAM-Nutzung zu reduzieren und die Gesamtleistung der BlueXP -Klassifizierung zu verbessern.

.Fehlerbehebungen
Fehler, die dazu geführt haben, dass StorageGRID-Scans fehlschlagen, dass die Filteroptionen für die Untersuchungsseite nicht geladen werden und die Datenermittlung, die für Prüfungen mit hohem Volumen nicht heruntergeladen werden sollte, wurden behoben.



=== Bis 14. April 2025



==== Version 1.42

Diese BlueXP -Klassifizierungsversion umfasst:

.Massenscans für Arbeitsumgebungen
Die BlueXP -Klassifizierung unterstützt Massenvorgänge für Arbeitsumgebungen. Sie können Mapping Scans aktivieren, Map & Classify Scans aktivieren, Scans deaktivieren oder eine benutzerdefinierte Konfiguration über Volumes in der Arbeitsumgebung erstellen. Wenn Sie eine Auswahl für ein einzelnes Volume treffen, wird die Massenauswahl überschrieben. Um einen Massenvorgang durchzuführen, navigieren Sie zur Seite **Konfiguration** und wählen Sie aus.

.Untersuchungsbericht lokal herunterladen
BlueXP  Classification unterstützt die Möglichkeit, Datenermittlungsberichte lokal herunterzuladen, um sie im Browser anzuzeigen. Wenn Sie die lokale Option wählen, ist die Datenermittlung nur im CSV-Format verfügbar und zeigt nur die ersten 10,000 Datenzeilen an.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten mit der BlueXP -Klassifizierung"].



=== 10 März 2025



==== Version 1.41

Diese BlueXP -Klassifizierungsversion enthält allgemeine Verbesserungen und Fehlerbehebungen. Die Lösung umfasst außerdem:

.Scanstatus
Die BlueXP -Klassifizierung verfolgt den Echtzeitfortschritt der Scans von _initial_ Mapping und Klassifikation auf einem Volume. Separate progressive Balken verfolgen die Mapping- und Klassifikations-Scans und zeigen einen Prozentsatz der insgesamt gescannten Dateien an. Sie können auch mit dem Mauszeiger auf eine Fortschrittsleiste zeigen, um die Anzahl der gescannten Dateien und die Gesamtdateien anzuzeigen. Durch das Verfolgen des Status Ihrer Scans erhalten Sie tiefere Einblicke in den Scanfortschritt, sodass Sie Ihre Scans besser planen und die Ressourcenzuweisung verstehen können.

Um den Status Ihrer Scans anzuzeigen, navigieren Sie in der BlueXP -Klassifizierung zu **Konfiguration**, und wählen Sie dann die **Konfiguration der Arbeitsumgebung**. Der Fortschritt wird für jedes Volume in der Zeile angezeigt.



=== 19 Februar 2025



==== Version 1.40

Diese BlueXP -Klassifizierungsversion umfasst die folgenden Updates.

.Unterstützung für RHEL 9.5
Diese Version bietet zusätzlich zu den zuvor unterstützten Versionen Unterstützung für Red hat Enterprise Linux 9.5. Dies gilt für alle manuellen On-Premises-Installationen von BlueXP -Klassifizierungen und Dark-Site-Bereitstellungen.

Für die folgenden Betriebssysteme ist die Verwendung der Podman-Container-Engine erforderlich, und sie erfordern eine BlueXP -Klassifizierung der Version 1.30 oder höher: Red hat Enterprise Linux der Version 8.8, 9.2, 9.0, 9.1, 8.10, 9.3, 9.4 und 9.5.

.Priorisieren Sie nur Mapping-Scans
Bei der Durchführung von nur-Mapping-Scans können Sie die wichtigsten Scans priorisieren. Diese Funktion hilft Ihnen, wenn Sie viele Arbeitsumgebungen haben und sicherstellen möchten, dass zuerst Scans mit hoher Priorität abgeschlossen werden.

Standardmäßig werden Scans basierend auf der Reihenfolge, in der sie initiiert werden, in die Warteschlange gestellt. Mit der Möglichkeit, Scans zu priorisieren, können Sie Scans an die Vorderseite der Warteschlange verschieben. Mehrere Scans können priorisiert werden. Die Priorität wird in der Reihenfolge „First-in“, „First-Out“ festgelegt. Das bedeutet, dass der erste von Ihnen priorisierte Scan an den Anfang der Warteschlange geht. Der zweite priorisierte Scan wird in der Warteschlange und so weiter.

Die Prioritätsachse wird einmalig vergeben. Automatische Neuscans von Zuordnungsdaten erfolgen in der Standardreihenfolge.

Die Priorisierung ist beschränkt auflink:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Nur-Mapping-Scans"^]; es ist nicht verfügbar für die Zuordnung und Klassifizierung von Scans.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["Priorisieren Sie Scans"^].

.Wiederholen Sie alle Scans
Die BlueXP -Klassifizierung unterstützt die Möglichkeit, alle fehlgeschlagenen Scans im Batch-Modus erneut zu versuchen.

Sie können Scans in einem Batch-Vorgang mit der Funktion **Alle wiederholen** erneut versuchen. Wenn Klassifikationsscans aufgrund eines vorübergehenden Problems, wie z. B. eines Netzwerkausfalls, fehlschlagen, können Sie alle Scans gleichzeitig mit einer Taste wiederholen, anstatt sie einzeln erneut zu versuchen. Scans können so oft wie nötig wiederholt werden.

So wiederholen Sie alle Scans:

. Wählen Sie im BlueXP -Klassifizierungsmenü *Konfiguration*.
. Um alle fehlgeschlagenen Scans erneut zu versuchen, wählen Sie *Alle Scans wiederholen*.


.Verbesserte Genauigkeit des Kategorisierungsmodells
Die Genauigkeit des Machine-Learning-Modells für link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["Vordefinierte Kategorien"] hat sich um 11 % erhöht.



=== 22 Januar 2025



==== Version 1.39

Diese BlueXP -Klassifizierungsversion aktualisiert den Exportprozess für den Datenuntersuchungsbericht. Diese Exportaktualisierung ist nützlich, um zusätzliche Analysen Ihrer Daten durchzuführen, zusätzliche Visualisierungen der Daten zu erstellen oder die Ergebnisse Ihrer Datenuntersuchung mit anderen zu teilen.

Zuvor war der Export des Berichts zur Untersuchung von Daten auf 10,000 Zeilen beschränkt. Mit dieser Version wurde das Limit entfernt, sodass Sie alle Ihre Daten exportieren können. Durch diese Änderung können Sie mehr Daten aus Ihren Datenermittlungsberichten exportieren, was Ihnen mehr Flexibilität bei der Datenanalyse bietet.

Sie können die Arbeitsumgebung, die Volumes, den Zielordner und entweder das JSON- oder CSV-Format auswählen. Der exportierte Dateiname enthält einen Zeitstempel, mit dem Sie den Zeitpunkt des Exportes der Daten identifizieren können.

Zu den unterstützten Arbeitsumgebungen gehören:

* Cloud Volumes ONTAP
* FSX für ONTAP
* ONTAP
* Gruppe freigeben


Das Exportieren von Daten aus dem Bericht zur Datenuntersuchung hat folgende Einschränkungen:

* Die maximale Anzahl der herunterzuladenen Datensätze beträgt 500 Millionen. Pro Typ (Dateien, Verzeichnisse und Tabellen)
* Eine Million Datensätze werden voraussichtlich etwa 35 Minuten für den Export benötigen.


Einzelheiten zur Datenermittlung und zum Bericht finden Sie unter https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Untersuchen Sie die in Ihrem Unternehmen gespeicherten Daten"].



=== Bis 16. Dezember 2024



==== Version 1.38

Diese BlueXP -Klassifizierungsversion enthält allgemeine Verbesserungen und Fehlerbehebungen.



== Cloud Volumes ONTAP



=== 14 Juli 2025



==== Unterstützung für transparenten Proxy

BlueXP unterstützt jetzt zusätzlich zu den bestehenden expliziten Proxy-Verbindungen transparente Proxy-Server. Beim Erstellen oder Ändern des BlueXP Connectors können Sie einen transparenten Proxy-Server konfigurieren, um den Netzwerkverkehr von und zu Cloud Volumes ONTAP sicher zu verwalten.

Weitere Informationen zur Verwendung von Proxyservern in Cloud Volumes ONTAP finden Sie unter:

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["Netzwerkkonfigurationen zur Unterstützung des Connector-Proxys in AWS"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["Netzwerkkonfigurationen zur Unterstützung des Connector-Proxys in Azure"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["Netzwerkkonfigurationen zur Unterstützung des Connector-Proxys in Google Cloud"^]




==== Neuer VM-Typ wird für Cloud Volumes ONTAP in Azure unterstützt

Ab Cloud Volumes ONTAP 9.13.1 wird L8s_v3 als VM-Typ in Azure-Einzel- und Mehrfachverfügbarkeitszonen sowohl für neue als auch für bestehende Hochverfügbarkeitspaarbereitstellungen (HA) unterstützt.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Unterstützte Konfigurationen in Azure"^].



=== 29 Mai 2025



==== Bereitstellungen im privaten Modus für Cloud Volumes ONTAP 9.15.1 aktiviert

Sie können Cloud Volumes ONTAP 9.15.1 jetzt im privaten Modus in AWS, Azure und Google Cloud bereitstellen. Der private Modus ist sowohl für Einzelknoten- als auch für Hochverfügbarkeitsbereitstellungen (HA) von Cloud Volumes ONTAP 9.15.1 aktiviert.

Weitere Informationen zu Bereitstellungen im privaten Modus finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["Weitere Informationen zu BlueXP Implementierungsmodi"^].



=== 12 Mai 2025



==== Bestandsaufnahme der Implementierungen, die über den Azure Marketplace in BlueXP  durchgeführt wurden

BlueXP  ist jetzt in der Lage, die Cloud Volumes ONTAP Systeme zu erkennen, die direkt über den Azure Marketplace bereitgestellt werden. Das bedeutet, dass Sie diese Systeme jetzt wie beliebige andere Cloud Volumes ONTAP-Systeme in BlueXP  als funktionierende Umgebungen hinzufügen und verwalten können.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Implementieren Sie Cloud Volumes ONTAP über den Azure Marketplace"^]



==== Möglichkeit zum Tiering von Daten für Azure Mandanten

Sie können nun das Tiering für einen Azure Mandanten in einem Szenario aktivieren, in dem die Cloud Volumes ONTAP Arbeitsumgebung von einem Mandanten erstellt und der BlueXP  Connector von einem anderen erstellt wird. Mithilfe dieser Funktion können Sie denselben Connector für das Tiering von Daten für mehrere Azure-Mandanten verwenden.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Anforderungen für das Tiering von Daten für einen Azure Mandanten"^]



== Cloud Volumes Service für Google Cloud



=== 9 September 2020



==== Unterstützung von Cloud Volumes Service für Google Cloud

Sie können Cloud Volumes Service für Google Cloud jetzt direkt über BlueXP verwalten:

* Einrichten und Erstellen einer Arbeitsumgebung
* Erstellen und managen Sie NFSv3 und NFSv4.1 Volumes für Linux- und UNIX-Clients
* Erstellen und managen Sie SMB 3.x Volumes für Windows Clients
* Erstellung, Löschung und Wiederherstellung von Volume Snapshots




== Kopieren und Synchronisieren



=== 2 Februar 2025



==== Unterstützung eines neuen Betriebssystems für Daten-Broker

Der Daten-Broker wird jetzt auf Hosts mit Red hat Enterprise 9.4, Ubuntu 23.04 und Ubuntu 24.04 unterstützt.

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["Linux-Host-Anforderungen anzeigen"].



=== 27 Oktober 2024



==== Fehlerbehebungen

Wir haben den BlueXP Kopier- und Synchronisierungsservice und den Daten-Broker aktualisiert, um einige Bugs zu beheben. Die neue Data Broker Version ist 1.0.56.



=== 16 September 2024



==== Fehlerbehebungen

Wir haben den BlueXP Kopier- und Synchronisierungsservice und den Daten-Broker aktualisiert, um einige Bugs zu beheben. Die neue Data Broker Version ist 1.0.55.



== Digitaler Berater



=== 08 Mai 2025



==== AutoSupport-Widget

Das Widget „AutoSupport“ wurde um ein Popup-Fenster erweitert, das Details zu Systemen enthält, die nicht mehr AutoSupport-Daten senden. Durch die Aktivierung von AutoSupport wird das Risiko von Ausfallzeiten verringert und ein proaktives Management des Systemzustands unterstützt.



==== Bericht zu Supportverträgen

Der Bericht „Supportverträge“ wurde um das neue ASP/LSG-Flag-Feld erweitert. Dieses Feld ermöglicht das Filtern und Identifizieren von Systemen, die von einem autorisierten Support-Partner abgedeckt werden, auch als Lifecycle Services Certified bekannt.



==== Dashboard zur Nachhaltigkeit

Über den in der Nachhaltigkeitspräsentation enthaltenen Link können Sie nun das Dashboard Nachhaltigkeit starten.



=== 05 März 2025



==== Upgrade Advisor

* Mit dem Disk Qualification Package (DQP) können Sie jetzt die Festplatten-Controller und die Firmware des Speichergeräts automatisch gemäß den vordefinierten Integrations- und Leistungskriterien aktualisieren. Dies verringert potenzielle Ausfälle und verbessert die allgemeine Systemzuverlässigkeit.
* Die Zeitzonendatenbank (DB) wurde eingeführt, um die Systemausrichtung automatisch mit den aktuellen Zeitzonendefinitionen zu halten. Dadurch wird sichergestellt, dass zeitabhängige Vorgänge auch dann reibungslos ablaufen, wenn sich die Zeitzonenregeln ändern.




=== Bis 12. Dezember 2024



==== Upgrade Advisor

Sie können jetzt die Speicherfirmware, die SP/BMC-Firmware und das Autonome Ransomware-Paket (ARP) anzeigen, die für ein Update empfohlen werden. link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["Erfahren Sie, wie Sie Empfehlungen für Firmware-Updates anzeigen"].



== Digitale Brieftasche



=== 10 März 2025



==== Möglichkeit zum Entfernen von Abonnements

Sie können Abonnements jetzt aus dem Digital Wallet entfernen, wenn Sie sie abbestellt haben.



==== Zeigen Sie die verbrauchte Kapazität für Marketplace-Abonnements an

Bei der Anzeige von PAYGO-Abonnements können Sie nun die verbrauchte Kapazität des Abonnements anzeigen.



=== 10 Februar 2025

Die BlueXP  Digital Wallet wurde aus Anwenderfreundlichkeit neu gestaltet und bietet jetzt zusätzliches Abonnement- und Lizenzmanagement.



==== Neues Dashboard mit Übersicht

Auf der Digital Wallet-Homepage befindet sich ein aktualisiertes Dashboard Ihrer NetApp Lizenzen und Marketplace Abonnements, in dem Sie nach bestimmten Services, Lizenztypen und erforderlichen Aktionen suchen können.



==== Konfigurieren von Abonnements für Anmeldeinformationen

Mit dem BlueXP  Digital Wallet können Sie jetzt Ihre Abonnements für Provider-Anmeldedaten konfigurieren. Normalerweise tun Sie dies, wenn Sie zum ersten Mal ein Marketplace-Abonnement oder einen Jahresvertrag abonnieren. Zuvor konnten die Anmeldeinformationen des Abonnements nur auf der Seite Anmeldedaten geändert werden.



==== Abonnements mit Organisationen verknüpfen

Sie können jetzt das Unternehmen, dem ein Abonnement zugeordnet ist, direkt aus dem Digital Wallet aktualisieren.



==== Management von Cloud Volume ONTAP Lizenzen

Sie verwalten jetzt Cloud Volumes ONTAP Lizenzen über die Startseite oder den Reiter *Direktlizenzen*. Verwenden Sie die Registerkarte *Marketplace-Abonnements*, um Ihre Abonnementinformationen anzuzeigen.



=== 5 März 2024



==== BlueXP Disaster Recovery

Mit der Digital Wallet von BlueXP können Sie Lizenzen für die Disaster Recovery von BlueXP jetzt managen. Sie können Lizenzen hinzufügen, Lizenzen aktualisieren und Details zur lizenzierten Kapazität anzeigen.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Managen Sie Lizenzen für BlueXP Datenservices"]



=== 30 Juli 2023



==== Verbesserte Nutzungsberichte

Die Berichte zur Cloud Volumes ONTAP-Nutzung wurden nun um einige Verbesserungen verbessert:

* Die tib-Einheit ist jetzt im Namen der Spalten enthalten.
* Ein neues _Node(s)_-Feld für Seriennummern ist nun enthalten.
* Im Bericht zur Auslastung von Storage-VMs wird jetzt eine neue Spalte „_Workload Type_“ angezeigt.
* Die Namen der Arbeitsumgebung sind jetzt in den Berichten zu Storage-VMs und Volume-Nutzung enthalten.
* Der Datenträgertyp _file_ wird nun mit _Primary (Read/Write)_ beschriftet.
* Der Datenträgertyp _secondary_ wird jetzt mit _secondary (DP)_ bezeichnet.


Weitere Informationen zu Nutzungsberichten finden Sie unter https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Nutzungsberichte herunterladen"].



== Disaster Recovery



=== 14 Juli 2025

Version 4.2.5



==== Benutzerrollen in der BlueXP disaster recovery

Die BlueXP disaster recovery verwendet jetzt Rollen, um den Zugriff jedes Benutzers auf bestimmte Funktionen und Aktionen zu regeln.

Der Dienst verwendet die folgenden Rollen, die spezifisch für die BlueXP disaster recovery sind.

* *Notfallwiederherstellungsadministrator*: Führen Sie beliebige Aktionen in der BlueXP disaster recovery durch.
* *Disaster Recovery-Failover-Administrator*: Führen Sie Failover- und Migrationsaktionen in der BlueXP disaster recovery durch.
* *Administrator der Notfallwiederherstellungsanwendung*: Erstellen und ändern Sie Replikationspläne und starten Sie Test-Failover.
* *Disaster Recovery Viewer*: Informationen in BlueXP disaster recovery anzeigen, aber keine Aktionen ausführen.


Wenn Sie auf den BlueXP disaster recovery klicken und ihn zum ersten Mal konfigurieren, müssen Sie über die Berechtigung *SnapCenterAdmin* verfügen oder die Rolle *Organisationsadministrator* innehaben.

Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Benutzerrollen und Berechtigungen in der BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen für alle Dienste"^].



==== Weitere Updates zur BlueXP disaster recovery

* Verbesserte Netzwerkerkennung
* Verbesserungen der Skalierbarkeit:
+
** Filtern nach den benötigten Metadaten statt nach allen Details
** Verbesserungen bei der Erkennung zum schnelleren Abrufen und Aktualisieren von VM-Ressourcen
** Speicheroptimierung und Leistungsoptimierung für Datenabruf und Datenaktualisierung
** Verbesserungen bei der Clienterstellung und Poolverwaltung im vCenter SDK


* Verwaltung veralteter Daten bei der nächsten geplanten oder manuellen Erkennung:
+
** Wenn eine VM im vCenter gelöscht wird, entfernt die BlueXP disaster recovery sie jetzt automatisch aus dem Replikationsplan.
** Wenn ein Datenspeicher oder Netzwerk im vCenter gelöscht wird, löscht die BlueXP disaster recovery es jetzt aus dem Replikationsplan und der Ressourcengruppe.
** Wenn ein Cluster, Host oder Rechenzentrum im vCenter gelöscht wird, löscht BlueXP disaster recovery es jetzt aus dem Replikationsplan und der Ressourcengruppe.


* Sie können jetzt im Inkognito-Modus Ihres Browsers auf die Swagger-Dokumentation zugreifen. Sie erreichen sie in BlueXP disaster recovery über die Option „Einstellungen“ > „API-Dokumentation“ oder direkt über die folgende URL im Inkognito-Modus Ihres Browsers:  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger-Dokumentation"^] .
* In manchen Fällen blieb die iGroup nach einem Failback-Vorgang bestehen. Dieses Update entfernt die iGroup, falls sie veraltet ist.
* Wenn der NFS-FQDN im Replikationsplan verwendet wurde, löst BlueXP disaster recovery ihn nun in eine IP-Adresse auf. Dieses Update ist nützlich, wenn der FQDN am Disaster Recovery-Standort nicht aufgelöst werden kann.
* Verbesserungen der UI-Ausrichtung
* Protokollverbesserungen zur Erfassung der vCenter-Größendetails nach der erfolgreichen Erkennung




=== 30 Juni 2025

Version 4.2.4P2



==== Verbesserungen bei der Erkennung

Dieses Update verbessert den Erkennungsprozess und verkürzt so die für die Erkennung benötigte Zeit.



=== 23 Juni 2025

Version 4.2.4P1



==== Verbesserungen der Subnetzzuordnung

Dieses Update erweitert den Dialog „Subnetzzuordnung hinzufügen und bearbeiten“ um eine neue Suchfunktion. Sie können nun schnell bestimmte Subnetze durch die Eingabe von Suchbegriffen finden, was die Verwaltung von Subnetzzuordnungen vereinfacht.



=== 9 Juni 2025

Version 4.2.4



==== Unterstützung für Windows Local Administrator Password Solution (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) ist eine Windows-Funktion, die das Kennwort eines lokalen Administratorkontos im Active Directory automatisch verwaltet und sichert.

Sie können nun Subnetzzuordnungsoptionen auswählen und die LAPS-Option aktivieren, indem Sie die Domänencontrollerdetails angeben. Mit dieser Option müssen Sie nicht für jede Ihrer virtuellen Maschinen ein Kennwort angeben.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



== E-Series Systeme



=== 12 Mai 2025



==== BlueXp-Zugriffsrolle erforderlich

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um E-Series in BlueXP anzuzeigen, zu entdecken oder zu verwalten: Organisationsadministrator, Ordner- oder Projektadministrator, Speicheradministrator oder Systemintegritätsspezialist.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



=== 18 September 2022



==== Unterstützung der E-Series

Ihre E-Series Systeme können jetzt direkt aus BlueXP heraus erkannt werden. Die Entdeckung von E-Series Systemen eröffnet Ihnen eine vollständige Ansicht der Daten in Ihrer Hybrid-Multi-Cloud.



== Wirtschaftliche Effizienz



=== 15 Mai 2024



==== Deaktivierte Funktionen

Einige der BlueXP  Funktionen zur wirtschaftlichen Effizienz wurden vorübergehend deaktiviert:

* Technologieaktualisierungen
* Kapazitäten ergänzen




=== 14 März 2024



==== Optionen für die Technologieaktualisierung

Wenn Sie bereits über Assets verfügen und feststellen möchten, ob eine Technologie aktualisiert werden muss, können Sie die wirtschaftlichen Effizienzoptionen von BlueXP nutzen. Sie können entweder eine kurze Bewertung Ihrer aktuellen Workloads überprüfen und Empfehlungen erhalten, oder wenn Sie in den vergangenen 90 Tagen AutoSupport-Protokolle an NetApp gesendet haben, kann der Service jetzt eine Workload-Simulation durchführen, um die Performance Ihrer Workloads auf neuer Hardware zu ermitteln.

Sie können auch einen Workload hinzufügen und vorhandene Workloads von der Simulation ausschließen.

Bisher konnten Sie nur eine Bewertung Ihrer Ressourcen vornehmen und feststellen, ob eine Technologieerneuerung empfohlen wird.

Die Funktion ist jetzt Teil der Option „Tech Refresh“ in der linken Navigation.

Erfahren Sie mehr über die https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["Bewertung einer Technologieaktualisierung"].



=== Bis 08. November 2023



==== Technologieaktualisierungen

Diese Version der wirtschaftlichen Effizienz von BlueXP enthält eine neue Option, mit der Sie Ihre Assets bewerten und feststellen können, ob eine Technologieaktualisierung empfohlen wird. Der Service umfasst eine neue Option zur technischen Aktualisierung in der linken Navigation, neue Seiten, auf denen Sie eine Bewertung Ihrer aktuellen Workloads und Ressourcen vornehmen können, sowie einen Bericht mit Empfehlungen für Sie.



== Edge-Caching

Der BlueXP  Edge Caching Service wurde am 7. August 2024 entfernt.



== Google Cloud Storage



=== 10 Juli 2023



==== Das Hinzufügen neuer Buckets und das Management vorhandener Buckets aus BlueXP ist möglich

Sie haben nun schon lange die Möglichkeit, Google Cloud Storage Buckets auf dem BlueXP Canvas anzuzeigen. Jetzt können Sie neue Buckets hinzufügen und Eigenschaften für vorhandene Buckets direkt aus BlueXP  ändern. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["So fügen Sie neue Google Cloud Storage Buckets hinzu"].



== Keystone



=== 19 Juni 2025



==== Keystone-Dashboard in BlueXP

Sie können jetzt direkt von BlueXP auf das Keystone-Dashboard zugreifen. Dank dieser Integration können Sie alle Ihre Keystone-Abonnements und Ihre anderen NetApp-Dienste zentral überwachen, verwalten und im Auge behalten.

Mit dem Keystone-Dashboard in BlueXP können Sie:

* Zeigen Sie alle Ihre Abonnementdetails, Kapazitätsnutzung und Assets an einem Ort an.
* Verwalten Sie Abonnements ganz einfach und fordern Sie Änderungen an, wenn sich Ihre Anforderungen ändern.
* Bleiben Sie mit den neuesten Informationen zu Ihrer Speicherumgebung auf dem Laufenden.


Um zu beginnen, gehen Sie im linken Navigationsmenü von BlueXP zu *Speicher > Keystone*. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Übersicht über Keystone Dashboard"].



== Kubernetes

Am 7. August 2024 wurde die Unterstützung für die Erkennung und das Management von Kubernetes-Clustern entfernt.



== Migrationsberichte

Der Service für BlueXP -Migrationsberichte wurde am 7. August 2024 aufgehoben.



== ONTAP-Cluster vor Ort



=== 12 Mai 2025



==== BlueXp-Zugriffsrolle erforderlich

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um lokale ONTAP-Cluster anzuzeigen, zu erkennen oder zu verwalten: Organisationsadministrator, Ordner- oder Projektadministrator, Speicheradministrator oder Systemintegritätsspezialist. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



=== Bis 26. November 2024



==== Unterstützung für ASA r2-Systeme mit Private Mode

Sie können jetzt NetApp ASA r2-Systeme erkennen, wenn Sie BlueXP  im privaten Modus verwenden. Diese Unterstützung ist ab der 3.9.46 Private Mode-Version von BlueXP  verfügbar.

* https://docs.netapp.com/us-en/asa-r2/index.html["Erfahren Sie mehr über ASA r2-Systeme"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Weitere Informationen zu BlueXP Implementierungsmodi"^]




=== 7 Oktober 2024



==== Unterstützung für ASA r2-Systeme

Sie können jetzt NetApp ASA r2-Systeme in BlueXP  erkennen, wenn Sie BlueXP  im Standardmodus oder im eingeschränkten Modus verwenden. Nachdem Sie ein NetApp ASA r2-System erkannt und die Arbeitsumgebung geöffnet haben, werden Sie direkt zu System Manager weitergeleitet.

Für ASA r2 Systeme sind keine anderen Managementoptionen verfügbar. Sie können die Standardansicht nicht verwenden und BlueXP Services nicht aktivieren.

Die Erkennung von ASA r2-Systemen wird nicht unterstützt, wenn BlueXP  im privaten Modus verwendet wird.

* https://docs.netapp.com/us-en/asa-r2/index.html["Erfahren Sie mehr über ASA r2-Systeme"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Weitere Informationen zu BlueXP Implementierungsmodi"^]




== Operative Ausfallsicherheit



=== Bis 02. April 2023



==== BlueXP  Service für die operative Ausfallsicherheit

Mithilfe des neuen BlueXP Service für betriebliche Ausfallsicherheit und seiner automatisierten Vorschläge zur Behebung DES IT-Betriebsrisikos können Sie vorgeschlagene Korrekturmaßnahmen implementieren, bevor es zu einem Ausfall oder einem Ausfall kommt.

Operational Resiliency ist ein Service, mit dem Sie Alarme und Ereignisse analysieren können, um den Zustand, die Uptime und die Performance von Services und Lösungen aufrechtzuerhalten.

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["Erfahren Sie mehr über die betriebliche Ausfallsicherheit von BlueXP"].



== Schutz durch Ransomware



=== 15 Juli 2025



==== SAN-Workload-Unterstützung

Diese Version unterstützt SAN-Workloads im BlueXP ransomware protection. Sie können jetzt zusätzlich zu NFS- und CIFS-Workloads auch SAN-Workloads schützen.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Voraussetzungen für den BlueXP Ransomware-Schutz"].



==== Verbesserter Workload-Schutz

Diese Version verbessert den Konfigurationsprozess für Workloads mit Snapshot- und Backup-Richtlinien aus anderen NetApp -Tools wie SnapCenter oder BlueXP backup and recovery. In früheren Versionen erkannte der BlueXP ransomware protection die Richtlinien anderer Tools und ermöglichte lediglich die Änderung der Erkennungsrichtlinie. Mit dieser Version können Sie nun Snapshot- und Backup-Richtlinien durch BlueXP ransomware protection Schutzrichtlinien ersetzen oder die Richtlinien anderer Tools weiterverwenden.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Schutz von Workloads"].



==== E-Mail-Benachrichtigungen

Wenn der BlueXP ransomware protection einen möglichen Angriff erkennt, wird eine Benachrichtigung in den BlueXP Benachrichtigungen angezeigt und eine E-Mail an die von Ihnen konfigurierte E-Mail-Adresse gesendet.

Die E-Mail enthält Informationen zum Schweregrad, zur betroffenen Arbeitslast und einen Link zur Warnung im Reiter „Warnungen“ des BlueXP ransomware protection .

Wenn Sie im BlueXP ransomware protection ein Sicherheits- und Ereignismanagementsystem (SIEM) konfiguriert haben, sendet der Dienst Warndetails an Ihr SIEM-System.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Behandeln Sie erkannte Ransomware-Warnmeldungen"].



=== 9 Juni 2025



==== Aktualisierungen der Zielseite

Diese Version enthält Aktualisierungen der Zielseite für den BlueXP-Ransomware-Schutz, die den Start der kostenlosen Testversion und die Entdeckung erleichtern.



==== Aktualisierungen der Bereitschaftsübung

Bisher konnten Sie eine Ransomware-Vorbereitungsübung durchführen, indem Sie einen Angriff auf eine neue Beispiel-Workload simulierten. Mit dieser Funktion können Sie den simulierten Angriff untersuchen und die Workload wiederherstellen. Nutzen Sie diese Funktion, um Warnmeldungen, Reaktionen und Wiederherstellung zu testen. Führen Sie diese Übungen so oft wie nötig durch und planen Sie sie.

Mit dieser Version können Sie über eine neue Schaltfläche im BlueXP-Dashboard zum Schutz vor Ransomware eine Ransomware-Bereitschaftsübung für eine Test-Workload ausführen. So können Sie Ransomware-Angriffe einfacher simulieren, ihre Auswirkungen untersuchen und Workloads effizient wiederherstellen – und das alles in einer kontrollierten Umgebung.

Sie können jetzt Bereitschaftsübungen zusätzlich zu NFS-Workloads auch für CIFS-Workloads (SMB) ausführen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Machen Sie sich eine Übung zur Vorbereitung auf einen Ransomware-Angriff"].



==== Aktivieren Sie BlueXP-Klassifizierungsaktualisierungen

Bevor Sie die BlueXP -Klassifizierung im BlueXP  Ransomware-Schutzservice verwenden, müssen Sie für den Scan Ihrer Daten die BlueXP -Klassifizierung aktivieren. Durch die Klassifizierung von Daten können Sie personenbezogene Daten (PII) finden, die das Sicherheitsrisiko erhöhen können.

Sie können die BlueXP-Klassifizierung auf einem Dateifreigabe-Workload aus dem BlueXP-Ransomware-Schutz heraus einsetzen. Wählen Sie in der Spalte „Datenschutzgefährdung“ die Option „Gefährdung identifizieren“ aus. Wenn Sie den Klassifizierungsdienst aktiviert haben, identifiziert diese Aktion die Gefährdung. Andernfalls wird in dieser Version ein Dialogfeld mit der Option zur Bereitstellung der BlueXP-Klassifizierung angezeigt. Wählen Sie „Bereitstellen“, um zur Startseite des BlueXP-Klassifizierungsdienstes zu gelangen und diesen Dienst dort bereitzustellen. W

Weitere Einzelheiten finden Sie unter  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["Implementieren Sie die BlueXP Klassifizierung in der Cloud"^] und um den Dienst innerhalb des BlueXP Ransomware-Schutzes zu nutzen, siehe  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["Suchen Sie mit der BlueXP -Klassifizierung nach personenbezogenen Daten"] .



=== 13 Mai 2025



==== Berichte zu nicht unterstützten Arbeitsumgebungen in BlueXP  Ransomware-Schutz

Während des Erkennungs-Workflows zeigt der BlueXP  Ransomware-Schutz weitere Details an, wenn Sie den Mauszeiger über unterstützte oder nicht unterstützte Workloads halten. So verstehen Sie, warum einige Ihrer Workloads nicht vom BlueXP  Ransomware-Schutzdienst erkannt werden.

Es gibt viele Gründe, warum der Dienst keine funktionierende Umgebung unterstützt. Beispielsweise könnte die ONTAP-Version in Ihrer Arbeitsumgebung unter der erforderlichen Version liegen. Wenn Sie den Mauszeiger über eine nicht unterstützte Arbeitsumgebung halten, wird in einer QuickInfo der Grund angezeigt.

Sie können die nicht unterstützten Arbeitsumgebungen während der ersten Erkennung anzeigen, in denen Sie die Ergebnisse auch herunterladen können. Sie können die Ergebnisse der Ermittlung auch über die Option *Workload-Erkennung* auf der Seite Einstellungen anzeigen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Workloads in BlueXP Ransomware-Schutz entdecken"].



=== Bis 29. April 2025



==== Unterstützung von Amazon FSX für NetApp ONTAP

Dieser Release unterstützt Amazon FSX für NetApp ONTAP. Diese Funktion hilft Ihnen mit BlueXP  Ransomware-Schutz dabei, Ihre FSX for ONTAP-Workloads zu schützen.

FSX for ONTAP ist ein vollständig gemanagter Service, der die Leistung von NetApp ONTAP Storage in der Cloud bereitstellt. Er bietet dieselben Funktionen, Performance- und Administrationsfunktionen, die Sie vor Ort nutzen, sowie die Agilität und Skalierbarkeit eines nativen AWS-Service.

Am Workflow für Ransomware-Schutz von BlueXP  wurden folgende Änderungen vorgenommen:

* Bestandsaufnahme umfasst Workloads in FSX for ONTAP 9.15 Arbeitsumgebungen.
* Auf der Registerkarte „Schutz“ werden Workloads in FSX für ONTAP-Umgebungen angezeigt. In dieser Umgebung sollten Sie Backup-Vorgänge mithilfe des FSX für ONTAP-Backup-Service durchführen. Sie können diese Workloads mit BlueXP  Snapshots zum Schutz vor Ransomware wiederherstellen.
+

TIP: Backup-Richtlinien für Workloads, die auf FSX for ONTAP ausgeführt werden, können nicht in BlueXP  festgelegt werden. Alle bestehenden Backup-Richtlinien in Amazon FSX für NetApp ONTAP bleiben unverändert.

* Warnungsvorfälle zeigen die neue Arbeitsumgebung von FSX for ONTAP.


Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Erfahren Sie mehr über BlueXP  Ransomware-Schutz und Arbeitsumgebungen"].

Informationen zu den unterstützten Optionen finden Sie im https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Einschränkungen beim BlueXP  Schutz vor Ransomware"].



==== BlueXp-Zugriffsrolle erforderlich

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um den BlueXP-Ransomware-Schutz anzuzeigen, zu erkennen oder zu verwalten: Organisationsadministrator, Ordner- oder Projektadministrator, Ransomware-Schutzadministrator oder Ransomware-Schutz-Betrachter.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen für alle Dienste"^].



=== Bis 14. April 2025



==== Bereitschaftsberichte

Mit dieser Version können Sie sich detaillierte Berichte zur Bereitschaft von Ransomware-Angriffen ansehen. Mit einer Bereitschaftsübung können Sie einen Ransomware-Angriff auf einen neu erstellten Beispiel-Workload simulieren. Untersuchen Sie dann den simulierten Angriff und stellen Sie den Proben-Workload wieder her. Diese Funktion hilft Ihnen dabei, sich im Falle eines echten Ransomware-Angriffs auf Sie vorzubereiten, indem Sie Warnmeldungs-, Reaktions- und Recovery-Prozesse testen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Machen Sie sich eine Übung zur Vorbereitung auf einen Ransomware-Angriff"].



==== Neue Rollen und Berechtigungen für die rollenbasierte Zugriffssteuerung

Bisher können Sie Benutzern Rollen und Berechtigungen basierend auf ihren Verantwortlichkeiten zuweisen, sodass Sie den Benutzerzugriff auf BlueXP  Ransomware-Schutz besser managen können. Mit dieser Version gibt es zwei neue Rollen speziell für den BlueXP  Ransomware-Schutz mit aktualisierten Berechtigungen. Die neuen Rollen sind:

* Administrator für Ransomware-Schutz
* Viewer für Ransomware-Schutz


Weitere Informationen zu Berechtigungen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["BlueXP  Ransomware-Schutz, rollenbasierter Zugriff auf Funktionen"].



==== Zahlungsverbesserungen

Diese Version enthält mehrere Verbesserungen am Zahlungsprozess.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Einrichten von Lizenz- und Zahlungsoptionen"].



== Korrekturmaßnahmen

Der BlueXP Service zur Problembehebung wurde am 22. April 2024 entfernt.



== Replizierung



=== 18 Sept. 2022



==== FSX für ONTAP auf Cloud Volumes ONTAP

Sie können jetzt Daten von einem Amazon FSX für ONTAP-Dateisystem auf Cloud Volumes ONTAP replizieren.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Hier erfahren Sie, wie Sie Datenreplizierung einrichten"].



=== 31 Juli 2022



==== FSX für ONTAP als Datenquelle

Sie können jetzt Daten von einem Amazon FSX für ONTAP-Dateisystem auf die folgenden Ziele replizieren:

* Amazon FSX für ONTAP
* On-Premises-ONTAP-Cluster


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Hier erfahren Sie, wie Sie Datenreplizierung einrichten"].



=== 2 September 2021



==== Unterstützung von Amazon FSX für ONTAP

Sie können jetzt Daten von einem Cloud Volumes ONTAP System oder einem lokalen ONTAP Cluster auf ein Amazon FSX für ONTAP Filesystem replizieren.

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["Hier erfahren Sie, wie Sie Datenreplizierung einrichten"].



== Software-Updates



=== 12 Mai 2025



==== BlueXp-Zugriffsrolle erforderlich

Sie benötigen nun eine der folgenden Zugriffsrollen, um Softwareupdates zu installieren: *Organisationsadministrator*, *Ordner- oder Projektadministrator*, *Speicheradministrator*, *Speicherbetrachter* oder *Speicherintegritätsspezialist*. Benutzer mit der Rolle „Speicherbetrachter“ verfügen über verschiedene Berechtigungen für Softwareupdates, können diese jedoch nicht installieren. link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



=== Bis 02. April 2025



==== Risikoverringerung

Im Abschnitt „Zusammenfassung“ der BlueXP -Softwareupdates können Sie nun die Gesamtzahl der Risiken anzeigen, die durch das Betriebssystem-Update vermindert werden können. Auf diese Weise können Benutzer die Sicherheits- und Stabilitätsverbesserungen auf ihrer Installationsbasis bewerten.



=== 07 August 2024



==== ONTAP-Update

Der BlueXP  Service für Softwareupdates bietet Benutzern ein nahtloses Update, da Risiken verringert und sichergestellt wird, dass Kunden die ONTAP Funktionen in vollem Umfang nutzen können.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  Software-Updates"].



== StorageGRID



=== 12 Mai 2025



==== Benötigte BlueXP -Zugriffsrollen

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um StorageGRID in BlueXP anzuzeigen, zu entdecken oder zu verwalten: *Organisationsadministrator*, *Ordner- oder Projektadministrator*, *Speicheradministrator* oder *Speicherintegritätsspezialist*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



=== 7 August 2024



==== Neue erweiterte Ansicht

Ab StorageGRID 11.8 können Sie das StorageGRID System über die vertraute Grid-Manager-Oberfläche von BlueXP  aus verwalten.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Erfahren Sie, wie Sie StorageGRID mithilfe der erweiterten Ansicht verwalten"].



==== Fähigkeit zur Überprüfung und Genehmigung des Zertifikats der StorageGRID Managementoberfläche

Sie können jetzt ein Zertifikat für die StorageGRID Managementoberfläche prüfen und genehmigen, wenn Sie das StorageGRID System von BlueXP  aus ermitteln. Sie können auch das neueste Zertifikat für die StorageGRID Managementoberfläche in einem erkannten Raster prüfen und genehmigen.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Erfahren Sie, wie Sie das Serverzertifikat während der Systemerkennung überprüfen und genehmigen."]



=== 18 September 2022



==== Unterstützung von StorageGRID

Sie können Ihre StorageGRID-Systeme jetzt direkt bei BlueXP entdecken. Die Entdeckung von StorageGRID verschafft Ihnen eine vollständige Übersicht über die Daten in Ihrer gesamten Hybrid-Multi-Cloud.



== Tiering



=== 9 August 2023



==== Verwenden Sie ein benutzerdefiniertes Präfix für den Bucket-Namen

In der Vergangenheit mussten Sie bei der Definition des Bucket-Namens das Standard-Präfix „Fabric-Pool“ verwenden, z. B. _Fabric-Pool-bucket1_. Jetzt können Sie beim Benennen Ihres Buckets ein benutzerdefiniertes Präfix verwenden. Diese Funktion ist nur beim Daten-Tiering zu Amazon S3 verfügbar. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Weitere Informationen ."].



==== Suchen Sie nach einem Cluster in allen BlueXP Connectors

Wenn Sie mehrere Connectors zur Verwaltung aller Speichersysteme in Ihrer Umgebung verwenden, befinden sich einige Cluster, auf denen Sie Tiering implementieren möchten, möglicherweise in verschiedenen Connectors. Wenn Sie sich nicht sicher sind, welcher Connector einen bestimmten Cluster managt, können Sie über alle Connectors hinweg mithilfe von BlueXP Tiering suchen. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Weitere Informationen ."].



=== 4 Juli 2023



==== Passen Sie die Bandbreite an, um inaktive Daten zu übertragen

Bei der Aktivierung von BlueXP Tiering kann ONTAP eine unbegrenzte Menge an Netzwerkbandbreite verwenden, um die inaktiven Daten von den Volumes im Cluster auf Objekt-Storage zu übertragen. Wenn Sie bemerken, dass der Tiering Traffic normale Benutzer-Workloads beeinträchtigt, können Sie die Bandbreite, die während der Übertragung verwendet werden kann, drosseln. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Weitere Informationen ."].



==== Tiering-Ereignis, das im Benachrichtigungscenter angezeigt wird

Das Tiering-Ereignis „Tiering zusätzlicher Daten von Cluster <name> auf Objekt-Storage zur Steigerung der Storage-Effizienz“ wird nun als Benachrichtigung angezeigt, wenn ein Cluster weniger als 20 % seiner kalten Daten Tiering durchführt – einschließlich Clustern, die keine Daten Tiering nutzen.

Diese Mitteilung ist eine „Empfehlung“, mit der Sie Ihre Systeme effizienter gestalten und Storage-Kosten einsparen können. Sie enthält einen Link zum https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP Tiering-Rechner für Gesamtbetriebskosten und Einsparungen"^] Zur Berechnung Ihrer Kosteneinsparungen.



=== Bis 3. April 2023



==== Die Registerkarte „Lizenzierung“ wurde entfernt

Die Registerkarte Lizenzierung wurde aus der BlueXP Tiering-Schnittstelle entfernt. Auf alle Lizenzen für PAYGO-Abonnements (Pay-as-you-go) kann jetzt über das BlueXP Tiering On-Premises-Dashboard zugegriffen werden. Über diesen Link gelangen Sie auch zur Digital Wallet von BlueXP, sodass Sie beliebige BlueXP Tiering-Lizenzen (BYOL, Bring-Your-Own-License) anzeigen und managen können.



==== Die Registerkarten „Tiering“ wurden umbenannt und aktualisiert

Die Registerkarte „Cluster Dashboard“ wurde in „Cluster“ umbenannt und die Registerkarte „On-Premises-Übersicht“ wurde in „On-Premises-Dashboard“ umbenannt. Auf diesen Seiten wurden einige Informationen hinzugefügt, die Ihnen helfen, zu bewerten, ob Sie Ihren Speicherplatz mit zusätzlicher Tiering-Konfiguration optimieren können.



== Volume-Caching



=== 04 Juni 2023



==== Volume-Caching

Volume Caching, eine Funktion der ONTAP 9 Software, ist eine Remote-Caching-Funktion, die die Dateiverteilung vereinfacht, WAN-Latenz reduziert, indem Ressourcen näher an den Orten Ihrer Benutzer und Computing-Ressourcen gebracht werden und die Kosten für die WAN-Bandbreite gesenkt werden. Durch Volume Caching wird ein persistentes, beschreibbares Volume an einem Remote-Standort bereitgestellt. BlueXP Volume-Caching beschleunigt den Zugriff auf Daten und erleichtert die Verlagerung von Datenverkehr von Volumes, auf die sehr viel zugegriffen wird. Cache Volumes sind ideal für leseintensive Workloads, insbesondere wenn Clients wiederholt auf dieselben Daten zugreifen müssen.

Mit BlueXP Volume-Caching verfügen Sie über Caching-Funktionen für die Cloud, insbesondere für Amazon FSX for NetApp ONTAP, Cloud Volumes ONTAP und On-Premises als Arbeitsumgebungen.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Weitere Informationen zum Volume-Caching von BlueXP"].



== Arbeitslast Fabrik



=== 29 Juni 2025



==== Berechtigungsaktualisierung für Datenbanken

Die folgende Berechtigung ist jetzt im _schreibgeschützten_ Modus für Datenbanken verfügbar:  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]



==== Unterstützung des BlueXP Workload Factory-Benachrichtigungsdienstes

Der Benachrichtigungsdienst der BlueXP Workload Factory ermöglicht es der Workload Factory, Benachrichtigungen an den BlueXP-Warndienst oder an ein Amazon SNS-Thema zu senden. An BlueXP-Warnmeldungen gesendete Benachrichtigungen werden im BlueXP-Warnmeldungsbereich angezeigt. Wenn die Workload Factory Benachrichtigungen an ein Amazon SNS-Thema veröffentlicht, erhalten Abonnenten des Themas (z. B. Benutzer oder andere Anwendungen) die Benachrichtigungen an den für das Thema konfigurierten Endpunkten (z. B. per E-Mail oder SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Konfigurieren Sie die Benachrichtigungen der BlueXP-Workload-Factory"]



=== 04 Mai 2025



==== Autocomplete-Unterstützung für CloudShell

Wenn Sie BlueXP  Workload Factory CloudShell verwenden, können Sie einen Befehl eingeben und die Tabulatortaste drücken, um die verfügbaren Optionen anzuzeigen. Wenn mehrere Möglichkeiten vorhanden sind, zeigt die CLI eine Liste mit Vorschlägen an. Diese Funktion steigert die Produktivität, indem Fehler minimiert und die Befehlsausführung beschleunigt wird.



==== Terminologie für Berechtigungen wurde aktualisiert

In der Benutzeroberfläche und Dokumentation der Workload Factory wird jetzt „schreibgeschützt“ für Leseberechtigungen und „Lesen/Schreiben“ für automatisierte Berechtigungen verwendet.



=== 30 März 2025



==== CloudShell meldet AI-generierte Fehlermeldungen für ONTAP-CLI-Befehle

Bei der Verwendung von CloudShell können Sie jedes Mal, wenn Sie einen ONTAP-CLI-Befehl ausgeben und ein Fehler auftritt, AI-generierte Fehlermeldungen erhalten, die eine Beschreibung des Fehlers, die Ursache des Fehlers und eine detaillierte Lösung enthalten.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Verwenden Sie CloudShell"]



==== iam:SimulatePermissionPolicy-Berechtigungsaktualisierung

Sie können jetzt die Berechtigung über die Konsole für die Werkseinstellungen managen `iam:SimulatePrincipalPolicy`, wenn Sie zusätzliche AWS-Kontoinformationen hinzufügen oder eine neue Workload-Funktion hinzufügen, z. B. den GenAI-Workload.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]



=== 02 Februar 2025



==== CloudShell ist in der BlueXP -Workload-Factory-Konsole verfügbar

CloudShell ist an jedem beliebigen Ort in der BlueXP -Workload-Factory-Konsole verfügbar. CloudShell ermöglicht Ihnen, die in Ihrem BlueXP -Konto angegebenen AWS- und ONTAP-Anmeldeinformationen zu verwenden und AWS CLI-Befehle oder ONTAP CLI-Befehle in einer Shell-ähnlichen Umgebung auszuführen.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Verwenden Sie CloudShell"]



==== Berechtigungsaktualisierung für Datenbanken

Die folgende Berechtigung ist jetzt im _read_ Modus für Datenbanken verfügbar: `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Änderungsprotokoll für Berechtigungen"]
